name: switch4eai
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - numpy=1.23.5
  - git
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu121
      - torch==2.3.0+cu121
      - torchvision==0.18.0+cu121
      - timm==0.9.12
      - lightning==2.3.0
      - hydra-core==1.3
      - hydra-zen
      - hydra_colorlog
      - rich
      - jupyter
      - matplotlib
      - ipdb
      - setuptools>=68.0
      - black
      - tensorboardX
      - opencv-python
      - ffmpeg-python
      - scikit-image
      - termcolor
      - einops
      - imageio==2.34.1
      - av==13.0.0
      - joblib
      - trimesh
      - chumpy
      - "smplx @ git+https://github.com/vchoutas/smplx"
      - wis3d
      - pycolmap
      - ultralytics==8.2.42
      - cython_bbox
      - lapx
      - "pytorch3d @ https://dl.fbaipublicfiles.com/pytorch3d/packaging/wheels/py310_cu121_pyt230/pytorch3d-0.7.6-cp310-cp310-linux_x86_64.whl"
      - loop_rate_limiters
      - mink
      - mujoco
      - scipy
      - "qpsolvers[proxqp]"
      - natsort
      - psutil
      - protobuf
      - "redis[hiredis]"
      - "imageio[ffmpeg]"
      - tqdm

